pygments: true
lis: true
markdown: "kramdown"

kramdown:
  use_coderay: true

  coderay:
    coderay_tab_width: 4

exclude: ["Gemfile", "Gemfile.lock", "Profile", "vendor", "sass", "static.rb", "config.rb", "config.ru", "*~", "*.swp"]

fullcalendar: "/fullcalendar-1.5.4/fullcalendar"
