pygments: true
lis: true
markdown: "maruku"

exclude: ["Gemfile", "Gemfile.lock", "Profile", "vendor", "sass", "static.rb", "config.rb", "config.ru"]

fullcalendar: "/fullcalendar-1.5.4/fullcalendar"
